#!/bin/bash
# QUICK START - Shell Scripting GUI
# Hướng dẫn nhanh cho Ubuntu 24.10

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   SHELL SCRIPTING GUI - QUICK START (Ubuntu 24.10)        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 BƯỚC 1: CÀI ĐẶT DEPENDENCIES"
echo "─────────────────────────────────────────────"
echo "Chạy lệnh sau để cài đặt Python3 và tkinter:"
echo ""
echo "  sudo apt update"
echo "  sudo apt install -y python3 python3-tk"
echo ""
echo "─────────────────────────────────────────────"
echo ""
echo "📋 BƯỚC 2: CẤP QUYỀN THỰC THI"
echo "─────────────────────────────────────────────"
echo "Chạy setup script (chỉ cần 1 lần):"
echo ""
echo "  chmod +x setup_gui.sh"
echo "  ./setup_gui.sh"
echo ""
echo "Hoặc cấp quyền thủ công:"
echo "  chmod +x gui_launcher.py launch_gui.sh"
echo "  chmod +x *.sh demo/*.sh file-management/*.sh"
echo "  chmod +x time-management/*.sh package-management/*.sh"
echo "  chmod +x task-scheduler/*.sh"
echo ""
echo "─────────────────────────────────────────────"
echo ""
echo "📋 BƯỚC 3: CHẠY GUI"
echo "─────────────────────────────────────────────"
echo "Chọn một trong các cách sau:"
echo ""
echo "  Cách 1: ./launch_gui.sh"
echo "  Cách 2: python3 gui_launcher.py"
echo "  Cách 3: ./gui_launcher.py"
echo ""
echo "─────────────────────────────────────────────"
echo ""
echo "💡 LƯU Ý:"
echo "  • GUI cần môi trường desktop (GNOME, KDE, etc.)"
echo "  • Nếu qua SSH: ssh -X user@host"
echo "  • Một số script cần quyền sudo"
echo ""
echo "📖 DOCUMENTATION:"
echo "  • Hướng dẫn chi tiết: GUI_README.md"
echo "  • Shell scripting docs: README.md"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Nhấn ENTER để thoát                                       ║"
echo "╚════════════════════════════════════════════════════════════╝"
read
